all: gtk-hello

GTK_CFLAGS=$(shell pkg-config gtk+-2.0 --cflags)
GTK_LDFLAGS=$(shell pkg-config gtk+-2.0 --libs)
CFLAGS_COMMON=-Wall -pedantic -g3 -O0

CFLAGS=$(CFLAGS_COMMON) $(GTK_CFLAGS) -std=gnu99
CXXFLAGS=$(CFLAGS_COMMON) $(GTK_CFLAGS) -std=gnu++0x

gtk-hello: gtk-hello.o
	g++ $(GTK_LDFLAGS) -o $@ $<

.c.o:
	gpp $(CFLAGS) -c -o $@ $<

.cpp.o:
	g++ $(CXXFLAGS) -c -o $@ $<

clean:
	rm -f *.a *.o gtk-hello

